### ISSUE TITLE
Error - blocking frame

### ISSUE THREAD

**Issue by technotip** [orange-games/phaser-ads#2]
Here is the error message I'm getting ..

```
ncaught TypeError: Cannot read property 'add' of undefinedcreate @ (index):49loadComplete @ phaser.js:30903preUpdate @ phaser.js:30670updateLogic @ phaser.js:39184update @ phaser.js:39071updateRAF @ phaser.js:62151_onLoop @ phaser.js:62135

VM333:1 Uncaught SecurityError: Blocked a frame with origin "http://imasdk.googleapis.com" from accessing a frame with origin "http://technotip.org". Protocols, domains, and ports must match.
```

**Comment by AleBles** [comment]
I get this on any iOS/OSX device, looking into it

**Comment by AleBles** [comment]
@technotip The 'add' of undefined seems to happen when you call request and ad, but no provider was set, if not, I'd like to see a basic example of what you're doing, if possible :)

As for the frame block, does it still happen with the latest version?
