### ISSUE TITLE
Question about ES6 import

### ISSUE THREAD

**Issue by RenaudROHLINGER** [orange-games/phaser-ads#31]
Hello,

Could this be possible to use one of your project in an ES6 project with just an import ? I don't work in typescript and don't really understand why there is no export feature in your projects, it looks like typescript doesn't need that.

You can close my issue right after your answer. I am just sad not being able to use any of your great projects :(

**Comment by RenaudROHLINGER** [comment]
Nevermind, I found a way.

**Comment by soylomass** [comment]
Could you please say how you solved it? I have the same problem.
